# Numpy & Pandas

## Numpy

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

# Khác list:
# - list chứa mọi thứ
# - array chỉ chứa 1 kiểu dữ liệu

[1 2 3]

In [2]:
# Array có thể là 1D, 2D, 3D, ... nD

b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]

In [3]:
# Các thao tác quan trọng
# 1. tạo nhanh
print(np.zeros((2,3)))   # toàn số 0
print(np.ones((2,3)))    # toàn số 1
print(np.arange(0,10))   # giống range

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]

In [4]:
# 2. Tính toán
a = np.array([1,2,3])
print(a + 10)     # [11,12,13]
print(a * 2)      # [2,4,6]
# list không làm được điều này

# 3. Truy cập phần tử
print(a[0])       # 1

# 4. thống kê nhanh 
print(np.mean(a))  # .mean() là hàm tính trung bình
print(np.max(a))   # .max() là hàm tính max
print(np.min(a))   # .min() là hàm tính min
print(np.sum(a))   # .sum() là hàm tính tổng

[11 12 13]
[2 4 6]
1
2.0
3
1
6

## Pandas

**Dùng để xử lý dữ liệu dạng bảng (giống Excel)**

In [2]:
import pandas as pd

data = {
    "name": ["An", "Bình", "Cường"],
    "age": [20, 21, 22]
}

df = pd.DataFrame(data)
print(df)

    name  age
0     An   20
1   Bình   21
2  Cường   22

In [1]:
# kiểm tra pyenv current
import sys
print(sys.executable)

c:\Users\ASUS\Documents\PROJECT\intro_to_AI\.venv\Scripts\python.exe

In [14]:
# Đọc file CSV

FILEPATH = "exports/employees.csv"
FILENAME = FILEPATH.split("/")[-1]
df = pd.read_csv(FILEPATH)

In [15]:
print("5 dòng đầu:", df.head())     # 5 dòng đầu
# print("5 dòng cuối:", df.tail())     # 5 dòng cuối
# print("Thông tin:", df.info())     # thông tin
# print("Thống kê:", df.describe()) # thống kê

5 dòng đầu:   Mã nhân viên     Họ tên  Năm sinh Giới tính  Số điện thoại  \
0        NV002    Hà Bình      2002        Nữ      921855621
1        NV003     Vũ Yên      1998       Nam      880349289
2        NV004  Phan Khoa      1989        Nữ      976425182
3        NV005      Tô An      1988        Nữ      970641615
4        NV006      Tạ An      2001        Nữ      828386636

                   Email     Địa chỉ      Phòng ban                Chức vụ  \
0    hàbình992@gmail.com     Cần Thơ        Nhân sự    nhân viên văn phòng
1     vũyên105@gmail.com  Bình Dương  Kĩ thuật viên               chủ tịch
2  phankhoa694@gmail.com         HCM        Nhân sự        quản lý cấp cao
3      tôan425@gmail.com         HCM        Kế toán      quản lý chi nhánh
4      tạan378@gmail.com    Hưng Yên        Nhân sự  tổ trưởng/trưởng nhóm

   Lương cơ bản  Ngày vào làm
0     9040121.0          2015
1    58099398.0          2015
2    36374390.0          2019
3    27780327.0          2016
4    23312384.0          2022

In [19]:
# lọc dữ liệu

df[df["Năm sinh"] == 2001]

,Mã nhân viên,Họ tên,Năm sinh,Giới tính,Số điện thoại,Email,Địa chỉ,Phòng ban,Chức vụ,Lương cơ bản,Ngày vào làm
4,NV006,Tạ An,2001,Nữ,828386636,tạan378@gmail.com,Hưng Yên,Nhân sự,tổ trưởng/trưởng nhóm,23312384.0,2022
7,NV009,Phạm Vân,2001,Nữ,852643459,phạmvân635@gmail.com,Cần Thơ,Giám đốc,nhân viên văn phòng,11717673.0,2023
12,NV014,Bùi Bình,2001,Nam,893503684,bùibình107@gmail.com,Hà Nội,IT,quản lý cấp cao,37379735.0,2016
20,NV022,Vũ An,2001,Nữ,820631269,vũan529@gmail.com,Cần Thơ,Kế toán,quản lý chi nhánh,25865325.0,2021

In [21]:
df["Họ tên"].head()

0      Hà Bình
1       Vũ Yên
2    Phan Khoa
3        Tô An
4        Tạ An
Name: Họ tên, dtype: object

In [23]:
df["Năm sinh"].mean()
# df["Năm sinh"].max()

np.float64(1995.64)

In [24]:
df.groupby("Năm sinh").count()

,Mã nhân viên,Họ tên,Giới tính,Số điện thoại,Email,Địa chỉ,Phòng ban,Chức vụ,Lương cơ bản,Ngày vào làm
Năm sinh,,,,,,,,,,
1985,3,3,3,3,3,3,3,3,3,3
1986,1,1,1,1,1,1,1,1,1,1
1987,2,2,2,2,2,2,2,2,2,2
1988,4,4,4,4,4,4,4,4,4,4
1989,4,4,4,4,4,4,4,4,4,4
1990,2,2,2,2,2,2,2,2,2,2
1991,2,2,2,2,2,2,2,2,2,2
1992,1,1,1,1,1,1,1,1,1,1
1993,2,2,2,2,2,2,2,2,2,2
1995,3,3,3,3,3,3,3,3,3,3
1996,1,1,1,1,1,1,1,1,1,1
1997,1,1,1,1,1,1,1,1,1,1
1998,1,1,1,1,1,1,1,1,1,1
1999,5,5,5,5,5,5,5,5,5,5
2000,2,2,2,2,2,2,2,2,2,2
2001,4,4,4,4,4,4,4,4,4,4
2002,2,2,2,2,2,2,2,2,2,2
2003,3,3,3,3,3,3,3,3,3,3
2004,4,4,4,4,4,4,4,4,4,4
2005,3,3,3,3,3,3,3,3,3,3